# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fb52d347dafe1a3e1c8e67b6c2a55a2764f242aa9e7bd61a02a50858e2c320af077f279b5df8fd812185c29fd4818bee7110cc106f71462ad965438782c7d83

test:
  secret_key_base: 1a468046dcf4018490ce1760cab2bab7dce997a4915c221f9336ea7c125a3749ca05e7ea0681ecf22870707ef5366d4b9adfcda0fccf3632b6ce04c55e9b4e62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
